apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  selector:
    matchLabels:
      app: gateway-service
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: gateway-lyk:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service-cs
  labels:
    app: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
    name: gateway-service-8080
  type: ClusterIP